language: scala
scala: 2.12.6
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"